name: electronicsshop_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.6
  http: ^1.3.0
  shared_preferences: ^2.5.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  image_picker: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
      - assets/images/
      - assets/images/headphones/
      - assets/images/smartwatch/
      - assets/images/ac/
      - assets/images/fridge/
      - assets/images/laptops/
      - assets/images/smartphones/
      - assets/images/televisions/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

